### ISSUE TITLE
Import musics 

### ISSUE THREAD

**Issue by christopho** [christopho/zelda_olb_se#6]
Musics from the original game are in .mid format, they should be converted to .ogg.

**Comment by Diarandor** [comment]
I recommend Audacity for the conversion. (This conversion can be done easily in less than 30 minutes, I think.)

**Comment by christopho** [comment]
Audacity cannot play .mid files for me, it can only edit them.

I did the conversion with

```
timidity -Ov *.mid
```

**Comment by christopho** [comment]
For future reference, this is how I did it with Ubuntu 14.04:

```
sudo apt-get install timidity
sudo service timidity start
timidity -Ov *.mid
```

But some instruments were missing, so I had to do this first to get a correct conversion: http://unix.stackexchange.com/questions/97883/timidity-no-instrument-mapped-to-tone-bank-0-no-idea-which-one-is-missing

**Comment by christopho** [comment]
Done https://github.com/christopho/zelda_olb_se/commit/3d790e7aabbc16e930aa6069a1523331c9d2b770
