### ISSUE TITLE
Donjon 7 - Walkthrough mécanismes

### ISSUE THREAD

**Issue by PhoenixII54** [christopho/zelda_olb_se#72]
Salle|Action|Effet
----- | ----- | -----
RC/E4|Tuer les deux octoroks|NORD
RC/E2|Interrupteur au sol|SUD
-|Coffre au trésor|PLAN
-1/B3|Coffre au trésor |CLEF
RC/B4|Interrupteur|EST
-1/B4|interrupteur sur l'ilot|OUEST
RC/A1|Tuer 2 octoroks|EST
A2|Coffre au trsor|BOUSSOLE
B2|interrupteur sur l'ilot|NORD
E1|Coffre au trésor|CLE
-1/D3|Coffre au trésor|CLE
E4|Tuer 2 octos|NORD
-1/D2|interrupteur sur ilot|EST
E1|Interrupteur|SUD
D1|interrupteur sur l'ilot|SUD
A1|Coffre au trésor|CLEF
-2/C4|Coffre nord|CLEF
B2|Coffre au trésor|CLEF
-|Interrupteur|SUD
B4|interrupteur|NORD
C4|Coffre est|PALMES
-1/C-D2|Coffre au trésor|CLEF
RC/C1|Coffre au trésor|GRANDE CLEF
-|interrupteur au sol|OUEST
-2/C2|boss|NORD
C1|-|GRAAL

**Comment by christopho** [comment]
Thanks!
