### ISSUE TITLE
Donjon 8 - Walkthrough

### ISSUE THREAD

**Issue by PhoenixII54** [christopho/zelda_olb_se#73]
SAlle|Action|Effet
---|---|---
RC/C6|Coffre au trésor|PLAN
D3|Coffre au trésor|CLEF
-1/C3|Interrupteur au sol|SUD
D3|Tuer soldat bleu|NORD
A2|interrupteur au sol|SUD
Salle AB1-2|chemin invisible entre les torches, au dessus des trous, accès à un coffre|CLEF
1er|Interrupteur au sol|NORD
BC3|Coffre au trésor|BOUSSOLE
RC/BC3|Coffre au trésor|CLEF
1er/C2|interrupteur|OUEST
D3|Mur fissuré caché|NORD
RC/A4|Coffre au trésor|CLEF
-1/B6|interrupteur au sol|NORD
A6|Coffre au trésor|CLEF
1er/A2|Mur fissuré invisible|NORD
A1|Coffre au trésor|CLEF
C1|Coffre au trésor|Grande CLEF
RC/A2|BOSS Armos|NORD
A1|Mur à exploser|EST
-|-|GRAAL+Plot twist !
A2|Coffre au trésor|Tunique bleue

**Comment by christopho** [comment]
Done, thanks!
