### ISSUE TITLE
Donjon secret : Mécanismes

### ISSUE THREAD

**Issue by PhoenixII54** [christopho/zelda_olb_se#81]
Salle|Action|Effet
-|-|-
C8|Interrupteur au sol|OUEST
H5|Murs fissurés cachés|NORD+SUD
B8|interrupteur au sol|SUD
C5|interrupteur au sol|OUEST
B5|interrupteur au sol|SUD
F5|Mur fissuré caché|NORD
BC1-2|Tuer tous les enemis|OUEST
B4|BOSS : Tigre géant (SoM)|NORD

**Comment by christopho** [comment]
Done
