### ISSUE TITLE
Donjon Final : Mécanismes

### ISSUE THREAD

**Issue by PhoenixII54** [christopho/zelda_olb_se#83]
Salle|Action|Effet
-|-|-
Rc/D5|interrupteur|OUEST
C3|BOSS 1 : Aghanim (fonctionnement identique à ROTH|NORD
C2|Téléporteur|Accès toit
1er/C2|Tuer soldat rouge|PETITE CLEF
D4|interrupteur|OUEST
A3|Tuer soldat rouge|EST
E3|tuer soldat rouge|OUEST
C1|tuer enemi|SUD
2è|D5|interrupteur|OUEST

Toit : Combat final VS Ganon -->GAME OVER !

**Comment by christopho** [comment]
Done
